# Helm values for Postgres chart

auth:
  enablePostgresUser: false
  username: "words"
  password: "password"
  database: "app"

primary:
  resourcesPreset: "medium"
  initdb:
    scriptsConfigMap: "postgres-db-init"
    user: "words"
    password: "password"
