apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-db-init
data:
  app.sql: |
    \c app

    CREATE TABLE nouns (
    id SERIAL PRIMARY KEY,
    noun TEXT NOT NULL
    );
    
    INSERT INTO nouns (noun) VALUES ('cat'), ('dog'), ('bird'), ('fish');
    
    CREATE TABLE verbs (
    id SERIAL PRIMARY KEY,
    verb TEXT NOT NULL
    );
    
    INSERT INTO verbs (verb) VALUES ('eat'), ('f**k'), ('marry'), ('kill');
