# -- Admission policy
# Ensures that pods all have liveness and readiness probes
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: pod-probes
spec:
  rules:
  - name: require-pod-probes
    match:
      any:
      - resources:
          kinds:
          - Pod
          namespaceSelector:
              matchExpressions:
                - key: type 
                  operator: In
                  values:
                  - "app-namespace"
                  - "db-namespace"
    validate:
      failureAction: Enforce
      message: "All pods require a liveness and a readiness probe."
      foreach:
      - list: request.object.spec.containers[]
        deny:
          conditions:
            all:
            - key: readinessProbe
              operator: AllNotIn
              value: "{{ element.keys(@)[] }}"
            - key: livenessProbe
              operator: AllNotIn
              value: "{{ element.keys(@)[] }}"
