apiVersion: v1
kind: Service
metadata:
  name: aggregator
  labels:
    app: aggregator
    service: aggregator
spec:
  selector:
    app: aggregator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
