apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: kube-system
  name: argocd
spec:
  targetNamespace: argocd
  createNamespace: true
  version: 7.7.16
  chart: argo-cd
  repo: https://argoproj.github.io/argo-helm
  valuesContent: |-
    configs:
      params:
        server.insecure: true

      repositories:
        grenade:
          type: git
          url: https://github.com/BioTheWolff/kube-grenade.git
          name: grenade
