apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: kube-system
  name: istio-base
spec:
  targetNamespace: istio-system
  createNamespace: true
  version: 1.25.2
  chart: base
  repo: https://istio-release.storage.googleapis.com/charts
  valuesContent: |-
    defaultRevision: default
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: kube-system
  name: istiod
spec:
  targetNamespace: istio-system
  createNamespace: true
  version: 1.25.2
  chart: istiod
  repo: https://istio-release.storage.googleapis.com/charts
