apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: openstack-cloud-controller-manager
  namespace: kube-system
spec:
  targetNamespace: kube-system
  version: 2.31.1
  chart: openstack-cloud-controller-manager
  repo: https://kubernetes.github.io/cloud-provider-openstack
  bootstrap: true
  valuesContent: |-
    secret:
      enabled: true
      name: cloud-config
      create: false

    nodeSelector:
      node-role.kubernetes.io/control-plane: "true"
