apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: restrict-db-access
  namespace: db-namespace
spec:
  endpointSelector:
    matchLabels:
      app: postgres
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: words
            namespace: app-namespace
      toPorts:
        - ports:
            - port: "5432"
              protocol: TCP
  egress:
    - {}
