apiVersion: v1
kind: Service
metadata:
  name: locust-master
spec:
  selector:
    app: locust-master
  ports:
    - protocol: TCP
      name: web
      port: 8089
      targetPort: loc-master-web
    - protocol: TCP
      name: p1
      port: 5557
      targetPort: loc-master-p1
    - protocol: TCP
      name: p2
      port: 5558
      targetPort: loc-master-p2
