apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  labels:
    name: locust-worker
spec:
  replicas: 5
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
        - name: locust-worker
          image: locustio/locust
          args: ["-f", "/locust/locust.py", "--worker", "--master-host", "$(LOCUST_MASTER)", "-H", "$(TARGET_HOST)"]
          env:
            - name: LOCUST_MASTER
              value: locust-master
            - name: TARGET_HOST
              value: "10.43.0.10"
          volumeMounts:
            - name: config
              mountPath: /locust
      volumes:
        - name: config
          configMap:
            name: locust
            items:
              - key: "locustfile.py"
                path: "locust.py"
